// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"GoLangTricks/src/wire_example/controller"
	"GoLangTricks/src/wire_example/mapper"
	"GoLangTricks/src/wire_example/service"
)

// Injectors from wire.go:

func InitWire() (*controller.HelloController, func(), error) {
	helloMapper := mapper.NewHelloMapper()
	helloService := service.NewHelloService(helloMapper)
	helloController := controller.NewHelloController(helloService)
	return helloController, func() {
	}, nil
}
